/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package meeting

class App {
    fun meeting(input: String): String {
        var result = input.split(';').map { colon_separated_fname_lname ->
            colon_separated_fname_lname.split(':').reversed().joinToString()
        }.sorted()
        return result.map { "(${it.uppercase()})" }.joinToString("")
    }
}

fun main(args: Array<String>) {
    println(App().meeting(args[0]))
}
